[package]
name = "thermal"
version = "0.1.0"
edition = "2018"

[dependencies]
color-eyre = "0.5.11"
codepage-437 = "0.1.0"
thiserror = "1.0.26"
rusb = "0.8.1"
tracing = "0.1.26"
tracing-subscriber = "0.2.19"
